version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: minimart_postgres
    restart: always
    environment:
      POSTGRES_DB: minimart_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: minimart_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@minimart.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
